### ISSUE TITLE
Not working in Xcode 7.3

### ISSUE THREAD

**Issue by litt1e-p** [markohlebar/Peckham#84]
Not working in Xcode 7.3?

**Comment by ClementPadovani** [comment]
Fixed in https://github.com/markohlebar/Peckham/commit/85ab4771889b76fbac3b276eb9027f5db010ea5f

Thanks, Clément

**Comment by ClementPadovani** [comment]
Please reopen the issue if the issue persists

**Comment by litt1e-p** [comment]
how to fix it in my Xcode 7.3?

**Comment by ClementPadovani** [comment]
Are you running the latest version of Alcatraz?

Thanks, Clément

**Comment by litt1e-p** [comment]
my Alcatraz version is 1.1.17, I have reInstall Peckham, but it's still not work

**Comment by ClementPadovani** [comment]
Alright, I'll check it out and get back to you.

**Comment by ClementPadovani** [comment]
Hum, Peckham seems to be working for me. 

![untitled 2](https://cloud.githubusercontent.com/assets/676023/13945584/c4c10458-f00e-11e5-9c22-a68a292d25da.png)

I’d suggest removing Alcatraz’s data (`~/Library/Application Support/Alcatraz` and `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`) and trying again.

**Comment by litt1e-p** [comment]
yeah! it works well after delete plug-ins as you said .thanks a lot

2016年3月22日星期二，ClementPadovani <notifications@github.com> 写道：

**Comment by ClementPadovani** [comment]
My pleasure.
